-- AlterTable
ALTER TABLE "Account" ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Asset" ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Liability" ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0;
